### ISSUE TITLE
Error in executing example 6

### ISSUE THREAD

**Issue by AniketSanjayDesai** [arkottke/pysra#14]
I got this error while running the example 6 given in PYSRA:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 20, in iter_geopsy_profiles
  File "<stdin>", line 20, in <listcomp>
NameError: name 'floa4t' is not defined

It was shown when executing this command:

fname = 'data/best100_GM_linux.txt'

for geopsy_profile in iter_geopsy_profiles(fname):
    profile = pysra.site.Profile([
        pysra.site.Layer(
            pysra.site.SoilType(
                'soil-%d' % i, l['density'] / pysra.site.GRAVITY,
                damping=0.05), l['thickness'], l['vel_shear'])
        for i, l in enumerate(geopsy_profile['layers'])
    ])
    # Use 1% damping for the half-space
    profile[-1].soil_type.damping = 0.01
    # Compute the waves from the last layer
    calc(ts, profile, profile.location('outcrop', index=-1))
    # Compute the site amplification
    outputs(calc)

The above was while running in python.

While running in Jupyter notebook, below error was shown:
TypeError                                 Traceback (most recent call last)
<ipython-input-12-7f247e10ca43> in <module>
     18         pysra.output.OutputLocation('outcrop', index=0),
     19         # Damping
---> 20         0.05
     21     ),
     22 

TypeError: __init__() takes 2 positional arguments but 3 were given

This was while executing the commands given in In[12] in the example 6.

**Comment by arkottke** [comment]
It looks like you might have inadvertently changed `float` to `floa4t` in the `iter_geopsy_profiles` function::

            cols = ['thickness', 'vel_comp', 'vel_shear', 'density']
            for _ in range(count):
                values = [float(p) for p in next(fp).split()]  # <-- HERE
                d['layers'].append(dict(zip(cols, values)))

            yield d

**Comment by AniketSanjayDesai** [comment]
Thank you Sir. It's working now. However, I have some queries.
1. in example 6, it's the linear elastic analysis. How can we do equivalent linear analysis by giving a single modulus reduction and damping ratio curve in input?
2. Example 5 gives randomization of modulus reduction and damping ratio curves and example 6 does ground response analysis of number of Vs profiles from Geopsy. I want to do both, i.e. taking 1000 or more Vs profiles from Geopsy as input and also randomization of modulus reduction and damping ratio curves and then do the ground response analysis. How to do that?
3. The output I also want in the form of Fourier spectrum at surface and Fourier amplification spectrum. How can I get that?

**Comment by arkottke** [comment]
@AniketSanjayDesai I don't have time to support you on all of these questions. I would recommend that you look through the examples, and then also the code. To understand the available outputs, look at: https://github.com/arkottke/pysra/blob/master/pysra/output.py
