### ISSUE TITLE
The maximum shear strain profile estimated in MaxStrainProfile is returning Array of strain values for a layer 

### ISSUE THREAD

**Issue by anismhd** [arkottke/pysra#6]
Dear sir,
While running a site response analysis, I came across the following problem.

Error:
The maximum shear strain profile estimated in MaxStrainProfile class for a layer is returning Array of strain values.

Possible reason:
Line 437, output.py: 
values = [0] + [l.strain for l in calc.profile[:-1]]

The above line can be modified as 
values = [0] + [l.strain_max for l in calc.profile[:-1]]
to obtain correct results.. 

Kindly confirm whether the above fix is ok...

**Comment by arkottke** [comment]
Thanks @anismhd for finding this issue. This has been corrected in v0.4.1, which will be sent to pypi after Github Webhooks are resolved (see https://twitter.com/githubstatus/status/1131255005909049345).
